### ISSUE TITLE
那么问题来了。如果有多个mock 文件，那不是要在main.js引用多次？

### ISSUE THREAD

**Issue by xgj1988** [tom-wong666/xiaoa#1]
那么问题来了。如果有多个mock 文件，那不是要在main.js引用多次？

**Comment by tom-wong666** [comment]
抱歉，刚看到这个Issues，相信你已经解决了这问题，但我还是回复一下：
看如下文件目录
./mock
   index.js
   MyInfo.js
项目main.js只引入了mock的index.js索引，index.js引用具体需要mock的数据(一组到N多组)，并将具体数据以http接口(一个到N过个)的形式抛出供页面使用。
综上，main.js不需要多次引用mock，所有mock数据在mock的index.js里面管理。
